"""Print every number the manuscript quotes, straight from the saved artefacts.

Writing results into a paper by hand is where transcription errors come from.
This script collects the values that appear in the text and tables into one
sheet (`outputs/paper_numbers.md`) so each claim in the manuscript can be
checked against the artefact that produced it.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import pandas as pd  # noqa: E402

METRIC_FILES = [
    ("Significance tests", "significance_summary.json"),
    ("Threshold sensitivity", "threshold_sensitivity_summary.json"),
    ("Calibration", "calibration_summary.json"),
    ("Error analysis", "error_analysis_summary.json"),
    ("Graph diagnostics", "graph_diagnostics.json"),
    ("Faithfulness", "faithfulness_summary.json"),
    ("Retraining ablations", "ablation_summary.json"),
    ("BTREP component ablation", "btrep_component_ablation_summary.json"),
    ("Scalability", "scalability_summary.json"),
    ("Explanation validation", "explanation_summary.json"),
]

TABLE_FILES = [
    ("Main detection results", "table03_main_detection_results.csv"),
    ("Efficiency and calibration", "table04_efficiency_calibration.csv"),
    ("Threshold sensitivity", "table06_threshold_sensitivity.csv"),
    ("Error analysis", "table08_error_analysis.csv"),
    ("Score distribution", "table09_score_distribution.csv"),
    ("Faithfulness", "table11_explanation_faithfulness.csv"),
    ("Local-only ablation", "table12_local_only_ablation.csv"),
    ("Split robustness", "table13_split_robustness.csv"),
    ("Unknown-node ablation", "table14_unknown_node_ablation.csv"),
    ("BTREP component ablation", "table15_btrep_component_ablation.csv"),
    ("Scalability", "table16_scalability.csv"),
    ("Explanation validation", "table17_explanation_validation.csv"),
]


def main() -> None:
    output_dir = ROOT / "outputs"
    lines: list[str] = [
        "# Numbers quoted in the manuscript",
        "",
        "Generated by `scripts/13_paper_numbers.py`. Every value below comes from a",
        "saved artefact; nothing here is typed by hand.",
        "",
    ]

    lines.append("## Metric summaries\n")
    for title, name in METRIC_FILES:
        path = output_dir / "metrics" / name
        lines.append(f"### {title} (`outputs/metrics/{name}`)\n")
        if not path.exists():
            lines.append("_not produced yet_\n")
            continue
        lines.extend(["```json", json.dumps(json.loads(path.read_text(encoding='utf-8')), indent=2), "```", ""])

    lines.append("## Tables\n")
    for title, name in TABLE_FILES:
        path = output_dir / "tables" / name
        lines.append(f"### {title} (`outputs/tables/{name}`)\n")
        if not path.exists():
            lines.append("_not produced yet_\n")
            continue
        df = pd.read_csv(path)
        lines.extend([df.round(4).to_markdown(index=False), ""])

    destination = output_dir / "paper_numbers.md"
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {destination} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
